apiVersion: modules.krateo.io/v1alpha1
kind: Core
metadata:
  name: krateo-module-core
spec:
  compositionSelector:
    matchLabels:
      platform: kubernetes
  organization: Krateo PlatformOps Company
  frontendUrl: http://192.46.238.64
  frontend:
    service:
      type: LoadBalancer
  backendUrl: http://172.104.231.64
  backend:
    service:
      type: LoadBalancer
  ingress:
    enabled: false
  lighthouse:
    enabled: false
  providers:
    github:
      clientId: 6b122931b6648eeffd51
      clientSecret: 60b2945b23c4258152abf9f88c971ee848f5d910
      token: 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
  auth:
    github:
      clientId: 6b122931b6648eeffd51
      clientSecret: 60b2945b23c4258152abf9f88c971ee848f5d910
      token: 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
  argo-cd:
    helmRelease:
      chart:
        version: 3.33.1
  ldap:
    enabled: false
  krateo-dashboard:
    version: 0.3.193
    frontend:
      image:
        repository: ghcr.io/krateoplatformops/krateo-dashboard-frontend
        tag: 1.3.22
        pullPolicy: Always
    backend:
      image:
        repository: ghcr.io/krateoplatformops/krateo-dashboard-backend
        tag: 1.3.51
        pullPolicy: Always
    postgresql:
      persistence:
        enabled: false
